export interface Artwork {
  id: string;
  title: string;
  titleEn?: string;
  year: number | null;
  medium: string;
  dimensions: string;
  category: "relief" | "objekt" | "installation" | "projekt";
  images: string[];
  image: string;
  description: string;
  status?: "available" | "sold" | "on-loan" | "not-for-sale";
  visible?: boolean;
  hiddenImages?: string[];
}

export const artworks: Artwork[] = [
  // ── RELIEFS ─────────────────────────────────────────────────────────────
  {
    id: "gelber-schatten",
    title: "Gelber Schatten",
    year: 2007,
    medium: "Filz, Acryl",
    dimensions: "165 × 125 cm",
    category: "relief",
    images: [
      "/images/gallery/gelber-schatten/_mg_3137.jpg",
      "/images/gallery/gelber-schatten/_mg_3139.jpg",
      "/images/gallery/gelber-schatten/_mg_3144.jpg",
      "/images/gallery/gelber-schatten/_mg_3156.jpg",
      "/images/gallery/gelber-schatten/_mg_3166.jpg",
      "/images/gallery/gelber-schatten/_mg_3174.jpg",
      "/images/gallery/gelber-schatten/_mg_3175.jpg",
      "/images/gallery/gelber-schatten/_mg_3188.jpg",
      "/images/gallery/gelber-schatten/_mg_3206.jpg",
      "/images/gallery/gelber-schatten/_mg_3207.jpg",
      "/images/gallery/gelber-schatten/_mg_3216.jpg",
      "/images/gallery/gelber-schatten/_mg_3218.jpg",
      "/images/gallery/gelber-schatten/_mg_3219.jpg",
      "/images/gallery/gelber-schatten/_mg_3411.jpg",
      "/images/gallery/gelber-schatten/_mg_3412.jpg",
    ],
    image: "/images/gallery/gelber-schatten/_mg_3137.jpg",
    description: "",
  },
  {
    id: "falscher-schatten",
    title: "Falscher Schatten",
    year: 2007,
    medium: "Filz, Acryl",
    dimensions: "90 × 90 cm",
    category: "relief",
    images: [
      "/images/gallery/falscher-schatten/_mg_3229.jpg",
      "/images/gallery/falscher-schatten/_mg_3230.jpg",
      "/images/gallery/falscher-schatten/_mg_3245.jpg",
      "/images/gallery/falscher-schatten/_mg_3278.jpg",
      "/images/gallery/falscher-schatten/_mg_3279.jpg",
      "/images/gallery/falscher-schatten/_mg_3281.jpg",
      "/images/gallery/falscher-schatten/_mg_3283.jpg",
      "/images/gallery/falscher-schatten/_mg_3285.jpg",
    ],
    image: "/images/gallery/falscher-schatten/_mg_3230.jpg",
    description: "",
  },
  {
    id: "ahnentafel",
    title: "Ahnentafel",
    year: 2007,
    medium: "Filz, Acryl",
    dimensions: "40 × 40 cm",
    category: "relief",
    images: [
      "/images/gallery/ahnentafel/_mg_3558.jpg",
      "/images/gallery/ahnentafel/_mg_3559.jpg",
      "/images/gallery/ahnentafel/_mg_3562.jpg",
      "/images/gallery/ahnentafel/_mg_3568.jpg",
      "/images/gallery/ahnentafel/_mg_3576.jpg",
    ],
    image: "/images/gallery/ahnentafel/_mg_3558.jpg",
    description: "",
  },
  {
    id: "mahlwerk",
    title: "Mahlwerk",
    year: 2009,
    medium: "Filz, Acryl",
    dimensions: "180 × 180 cm",
    category: "relief",
    images: [
      "/images/gallery/mahlwerk/bild0390.jpg",
      "/images/gallery/mahlwerk/bild0391.jpg",
      "/images/gallery/mahlwerk/bild0392.jpg",
      "/images/gallery/mahlwerk/bild0393.jpg",
      "/images/gallery/mahlwerk/bild0394.jpg",
      "/images/gallery/mahlwerk/bild0395.jpg",
      "/images/gallery/mahlwerk/bild0396.jpg",
      "/images/gallery/mahlwerk/bild0397.jpg",
      "/images/gallery/mahlwerk/img_0302.jpg",
      "/images/gallery/mahlwerk/img_0387.jpg",
    ],
    image: "/images/gallery/mahlwerk/bild0394.jpg",
    description: "",
  },
  {
    id: "freier-fall",
    title: "Freier Fall",
    year: 2008,
    medium: "Filz auf Leinwand",
    dimensions: "65 × 65 × 10 cm",
    category: "relief",
    images: [
      "/images/gallery/freier-fall/dsc00144.jpg",
      "/images/gallery/freier-fall/img_0273.jpg",
      "/images/gallery/freier-fall/img_0281.jpg",
    ],
    image: "/images/gallery/freier-fall/dsc00144.jpg",
    description: "",
  },
  {
    id: "strudel",
    title: "Strudel",
    year: 2011,
    medium: "Filz, Acryl",
    dimensions: "43 × 43 cm",
    category: "relief",
    images: [
      "/images/gallery/strudel/dsc00118.jpg",
      "/images/gallery/strudel/dsc00119.jpg",
      "/images/gallery/strudel/dsc00120.jpg",
      "/images/gallery/strudel/dsc00122.jpg",
      "/images/gallery/strudel/dsc00124.jpg",
      "/images/gallery/strudel/dsc00176.jpg",
    ],
    image: "/images/gallery/strudel/dsc00118.jpg",
    description: "",
  },
  {
    id: "entscheidung",
    title: "Entscheidung",
    year: 2012,
    medium: "Filz auf Leinwand",
    dimensions: "130 × 115 cm",
    category: "relief",
    images: [
      "/images/gallery/entscheidung/dsc00478.jpg",
      "/images/gallery/entscheidung/dsc00518.jpg",
      "/images/gallery/entscheidung/dsc00534.jpg",
      "/images/gallery/entscheidung/dsc00550.jpg",
      "/images/gallery/entscheidung/dsc00556.jpg",
      "/images/gallery/entscheidung/dsc00559_2.jpg",
      "/images/gallery/entscheidung/dsc00565_2.jpg",
    ],
    image: "/images/gallery/entscheidung/dsc00534.jpg",
    description: "",
  },
  {
    id: "entscheidung-bunt",
    title: "Entscheidung bunt",
    year: 2013,
    medium: "Filz, Acryl",
    dimensions: "",
    category: "relief",
    images: [
      "/images/gallery/entscheidung-bunt/entscheidung-bunt-1.jpg",
    ],
    image: "/images/gallery/entscheidung-bunt/entscheidung-bunt-1.jpg",
    description: "",
  },
  {
    id: "entscheidung-weiss",
    title: "Entscheidung weiß",
    year: 2013,
    medium: "Filz, Acryl",
    dimensions: "",
    category: "relief",
    images: [
      "/images/gallery/entscheidung-weiss/entscheidung-weiss-1.jpg",
      "/images/gallery/entscheidung-weiss/entscheidung-weiss-2.jpg",
    ],
    image: "/images/gallery/entscheidung-weiss/entscheidung-weiss-1.jpg",
    description: "",
  },
  {
    id: "experiment",
    title: "Experiment",
    year: 2012,
    medium: "Filz, Acryl",
    dimensions: "",
    category: "relief",
    images: [
      "/images/gallery/experiment/dsc00425.jpg",
      "/images/gallery/experiment/dsc00434_2.jpg",
      "/images/gallery/experiment/dsc00448_2.jpg",
      "/images/gallery/experiment/dsc00439.jpg",
      "/images/gallery/experiment/dsc00436_2.jpg",
      "/images/gallery/experiment/dsc00421_2.jpg",
      "/images/gallery/experiment/dsc00429.jpg",
    ],
    image: "/images/gallery/experiment/dsc00425.jpg",
    description: "",
  },
  {
    id: "bewegte-tiefe-1",
    title: "Bewegte Tiefe 1",
    year: 2015,
    medium: "Filz, Acryl",
    dimensions: "",
    category: "relief",
    images: [
      "/images/gallery/bewegte-tiefe-1/bewegte-tiefe-1.jpg",
    ],
    image: "/images/gallery/bewegte-tiefe-1/bewegte-tiefe-1.jpg",
    description: "",
  },
  {
    id: "bewegte-tiefe-2",
    title: "Bewegte Tiefe 2",
    year: 2015,
    medium: "Filz, Acryl",
    dimensions: "",
    category: "relief",
    images: [
      "/images/gallery/bewegte-tiefe-2/bewegte-tiefe-2.jpg",
    ],
    image: "/images/gallery/bewegte-tiefe-2/bewegte-tiefe-2.jpg",
    description: "",
  },
  {
    id: "herz",
    title: "Herz",
    year: 2013,
    medium: "Filz, Acryl",
    dimensions: "",
    category: "relief",
    images: [
      "/images/gallery/herz/herz-freigelaegt.jpg",
      "/images/gallery/herz/herz-2.jpg",
    ],
    image: "/images/gallery/herz/herz-freigelaegt.jpg",
    description: "",
  },
  {
    id: "waagerechte",
    title: "Waagerechte",
    year: null,
    medium: "Filz, Acryl auf Nessel",
    dimensions: "84 × 84 cm (1 + 2)",
    category: "relief",
    images: [
      "/images/gallery/waagerechte/_mg_3433.jpg",
      "/images/gallery/waagerechte/_mg_3435.jpg",
    ],
    image: "/images/gallery/waagerechte/_mg_3433.jpg",
    description: "",
  },
  {
    id: "herbst-mulde",
    title: "Herbst Mulde",
    year: null,
    medium: "Filz, Acryl",
    dimensions: "45 × 45 cm",
    category: "relief",
    images: [
      "/images/gallery/herbst-mulde/dsc00319_2.jpg",
      "/images/gallery/herbst-mulde/dsc00320_2.jpg",
    ],
    image: "/images/gallery/herbst-mulde/dsc00319_2.jpg",
    description: "",
  },
  {
    id: "insel",
    title: "Insel",
    year: null,
    medium: "Filz, Acryl",
    dimensions: "45 × 45 cm",
    category: "relief",
    images: [
      "/images/gallery/insel/img_0324.jpg",
      "/images/gallery/insel/img_0369.jpg",
    ],
    image: "/images/gallery/insel/img_0324.jpg",
    description: "",
  },
  {
    id: "maulwurf",
    title: "Maulwurf",
    year: null,
    medium: "Filz, Acryl",
    dimensions: "45 × 45 cm",
    category: "relief",
    images: [
      "/images/gallery/maulwurf/dsc00390_2.jpg",
      "/images/gallery/maulwurf/dsc00391_2.jpg",
      "/images/gallery/maulwurf/dsc00392_2.jpg",
      "/images/gallery/maulwurf/dsc00393_2.jpg",
    ],
    image: "/images/gallery/maulwurf/dsc00390_2.jpg",
    description: "",
  },
  {
    id: "domino",
    title: "Domino",
    year: null,
    medium: "Filz, Acryl",
    dimensions: "120 × 80 cm",
    category: "relief",
    images: [
      "/images/gallery/domino/domino-1.jpg",
      "/images/gallery/domino/dsc00403.jpg",
      "/images/gallery/domino/domino-seit.png",
    ],
    image: "/images/gallery/domino/domino-1.jpg",
    description: "",
  },
  {
    id: "mehr-liebe",
    title: "Mehr Liebe braucht das Land",
    year: null,
    medium: "Filz, Acryl auf Holzplatte",
    dimensions: "21 × 21 cm",
    category: "relief",
    images: [
      "/images/gallery/mehr-liebe/dsc00454.jpg",
      "/images/gallery/mehr-liebe/dsc00449_2.jpg",
    ],
    image: "/images/gallery/mehr-liebe/dsc00454.jpg",
    description: "",
  },
  {
    id: "rote-blueten",
    title: "Rote Blüten",
    year: 2001,
    medium: "Filz, Acryl auf Leinwand",
    dimensions: "4-teilig, je 35 × 35 cm",
    category: "relief",
    images: [
      "/images/gallery/rote-blueten/_mg_3345.jpg",
      "/images/gallery/rote-blueten/_mg_3351.jpg",
      "/images/gallery/rote-blueten/_mg_3359.jpg",
      "/images/gallery/rote-blueten/_mg_3364.jpg",
    ],
    image: "/images/gallery/rote-blueten/_mg_3351.jpg",
    description: "",
  },
  {
    id: "drei-goetzen",
    title: "Drei Götzen",
    year: 2000,
    medium: "Filz, Acryl",
    dimensions: "3-teilig, je 40 × 40 cm",
    category: "relief",
    images: [
      "/images/gallery/drei-goetzen/010_07.jpg",
      "/images/gallery/drei-goetzen/011_08.jpg",
      "/images/gallery/drei-goetzen/012_09.jpg",
    ],
    image: "/images/gallery/drei-goetzen/010_07.jpg",
    description: "",
  },

  {
    id: "morse-text",
    title: "Morse Text",
    year: 1999,
    medium: "Filz, Acryl",
    dimensions: "145 × 45 cm",
    category: "relief",
    images: ["/images/gallery/morse-text/morse-text.svg"],
    image: "/images/gallery/morse-text/morse-text.svg",
    description: "Ein in Morse-Code übersetzter Text als abstraktes Relief – lesbar für alle, die die Sprache kennen.",
  },
  // ── OBJEKTE ─────────────────────────────────────────────────────────────
  {
    id: "mahnstufe-1",
    title: "Mahnstufe 1",
    year: 2000,
    medium: "Originale Mausefallen im Glaskasten",
    dimensions: "142 × 42 × 8 cm",
    category: "objekt",
    images: [
      "/images/gallery/mahnstufe-1/_mg_3415.jpg",
      "/images/gallery/mahnstufe-1/_mg_3416.jpg",
      "/images/gallery/mahnstufe-1/_mg_3417.jpg",
      "/images/gallery/mahnstufe-1/wiedermann-11.jpg",
      "/images/gallery/mahnstufe-1/wiedermann-11b.jpg",
    ],
    image: "/images/gallery/mahnstufe-1/_mg_3415.jpg",
    description: "",
  },
  {
    id: "regalsystem-saly",
    title: "Regalsystem Saly",
    year: null,
    medium: "Möbel",
    dimensions: "",
    category: "objekt",
    images: [
      "/images/gallery/regalsystem-saly/img0001_2.jpg",
      "/images/gallery/regalsystem-saly/img0010_2.jpg",
      "/images/gallery/regalsystem-saly/img0011_2.jpg",
      "/images/gallery/regalsystem-saly/img0017_2.jpg",
      "/images/gallery/regalsystem-saly/img0020_2.jpg",
      "/images/gallery/regalsystem-saly/img0031_2.jpg",
    ],
    image: "/images/gallery/regalsystem-saly/img0001_2.jpg",
    description: "",
  },
  {
    id: "garderobe",
    title: "Garderobe",
    year: null,
    medium: "Möbel",
    dimensions: "",
    category: "objekt",
    images: [
      "/images/gallery/garderobe/garde.jpg",
      "/images/gallery/garderobe/schpiegel.jpg",
      "/images/gallery/garderobe/kugel.jpg",
    ],
    image: "/images/gallery/garderobe/garde.jpg",
    description: "",
  },
  {
    id: "duftlaempchen",
    title: "Duftlämpchen",
    year: null,
    medium: "Objekt",
    dimensions: "",
    category: "objekt",
    images: [
      "/images/gallery/duftlaempchen/duftlampe-kopie.jpg",
    ],
    image: "/images/gallery/duftlaempchen/duftlampe-kopie.jpg",
    description: "",
  },
  {
    id: "schmuckkaestchen",
    title: "Schmuckkästchen",
    year: null,
    medium: "Objekt",
    dimensions: "",
    category: "objekt",
    images: [
      "/images/gallery/schmuckkaestchen/schmuckkaestchen-o1-kopie.jpg",
      "/images/gallery/schmuckkaestchen/schmuckkaestchen-kopie.jpg",
    ],
    image: "/images/gallery/schmuckkaestchen/schmuckkaestchen-o1-kopie.jpg",
    description: "",
  },
  {
    id: "staffelei",
    title: "Staffelei",
    year: null,
    medium: "Möbel",
    dimensions: "",
    category: "objekt",
    images: [
      "/images/gallery/staffelei/staffelei-kopie.jpg",
      "/images/gallery/staffelei/staffelei-o1-kopie.jpg",
      "/images/gallery/staffelei/staffelei-detail-o3-kopie.jpg",
      "/images/gallery/staffelei/staffelei-detail-kopie.jpg",
      "/images/gallery/staffelei/staffelei-detail-o2-kopie.jpg",
    ],
    image: "/images/gallery/staffelei/staffelei-kopie.jpg",
    description: "",
  },
  // ── INSTALLATIONEN ──────────────────────────────────────────────────────
  {
    id: "paradigma",
    title: "Paradigma",
    year: null,
    medium: "Installation",
    dimensions: "",
    category: "installation",
    images: [
      "/images/gallery/paradigma/front-annsicht.jpg",
      "/images/gallery/paradigma/front-annsicht-tiff.jpg",
      "/images/gallery/paradigma/front-annsicht-weisz-hinterg.jpg",
      "/images/gallery/paradigma/links-tiff.jpg",
      "/images/gallery/paradigma/rechts-tiff.jpg",
      "/images/gallery/paradigma/deteil-puppe-1.jpg",
      "/images/gallery/paradigma/deteil-puppe-2.jpg",
      "/images/gallery/paradigma/deteil-puppe-3.jpg",
      "/images/gallery/paradigma/deteil-midizin.jpg",
      "/images/gallery/paradigma/deteil-mos.jpg",
      "/images/gallery/paradigma/deteil-rose-1.jpg",
      "/images/gallery/paradigma/deteil-rose-2.jpg",
      "/images/gallery/paradigma/deteil-rose-3.jpg",
      "/images/gallery/paradigma/deteil-wurzel.jpg",
    ],
    image: "/images/gallery/paradigma/front-annsicht.jpg",
    description: "Foyerarbeit",
  },
  // ── PROJEKTE ────────────────────────────────────────────────────────────
  {
    id: "rinder",
    title: "Rinder",
    year: null,
    medium: "Projekt",
    dimensions: "",
    category: "projekt",
    images: [
      "/images/gallery/rinder/rinder-kopie.jpg",
      "/images/gallery/rinder/bos-taurus-sw1.jpg",
      "/images/gallery/rinder/praegung-mit-stemp.jpg",
      "/images/gallery/rinder/saal-inst.-in-farbe-jpg.jpg",
      "/images/gallery/rinder/saal-inst.in-sw-jpg.jpg",
      "/images/gallery/rinder/sall-inst-2-in-sw.jpg",
      "/images/gallery/rinder/rinder-o1-kopie.jpg",
      "/images/gallery/rinder/rinder-o2-kopie.jpg",
      "/images/gallery/rinder/foto-5.jpg",
      "/images/gallery/rinder/bostaurus-rinder-kopf.jpg",
      "/images/gallery/rinder/blatt-schraegansicht.jpg",
      "/images/gallery/rinder/blatt-frontansicht.jpg",
      "/images/gallery/rinder/saal.jpg",
      "/images/gallery/rinder/1-saal-1-2.jpg",
    ],
    image: "/images/gallery/rinder/rinder-kopie.jpg",
    description: "",
  },
  {
    id: "mausefalle",
    title: "Mausefalle",
    year: 1999,
    medium: "Stahl, Holz",
    dimensions: "",
    category: "projekt",
    images: [
      "/images/gallery/mausefalle/mausefalle-kopie.jpg",
      "/images/gallery/mausefalle/mausefalle-o1-kopie.jpg",
    ],
    image: "/images/gallery/mausefalle/mausefalle-kopie.jpg",
    description: "",
  },
  {
    id: "sonnensegel",
    title: "Sonnensegel",
    year: null,
    medium: "Architektur",
    dimensions: "",
    category: "projekt",
    images: [
      "/images/gallery/sonnensegel/sonnensegel-kopie.jpg",
      "/images/gallery/sonnensegel/sonnensegel-detail-kopie.jpg",
    ],
    image: "/images/gallery/sonnensegel/sonnensegel-kopie.jpg",
    description: "",
  },
  {
    id: "tueren",
    title: "Türen",
    year: null,
    medium: "Architektur",
    dimensions: "",
    category: "projekt",
    images: [
      "/images/gallery/tueren/_mg_3134.jpg",
      "/images/gallery/tueren/bild-tuer-ohne-datum.jpg",
      "/images/gallery/tueren/dsc00071.jpg",
      "/images/gallery/tueren/dsc00084.jpg",
      "/images/gallery/tueren/dsc00086.jpg",
      "/images/gallery/tueren/dsc00088.jpg",
      "/images/gallery/tueren/dsc00092.jpg",
      "/images/gallery/tueren/dsc00093.jpg",
      "/images/gallery/tueren/dsc00368_2.jpg",
    ],
    image: "/images/gallery/tueren/_mg_3134.jpg",
    description: "",
  },
  {
    id: "fotogalerie",
    title: "Fotogalerie",
    year: null,
    medium: "Fotografie",
    dimensions: "",
    category: "projekt",
    images: [
      "/images/gallery/fotogalerie/dsc00072.jpg",
      "/images/gallery/fotogalerie/dsc00081.jpg",
      "/images/gallery/fotogalerie/_mg_3133.jpg",
      "/images/gallery/fotogalerie/dsc00076.jpg",
    ],
    image: "/images/gallery/fotogalerie/dsc00072.jpg",
    description: "",
  },
  {
    id: "commode",
    title: "Commode",
    year: null,
    medium: "Restaurierung",
    dimensions: "",
    category: "projekt",
    images: [
      "/images/gallery/commode/fertig.jpg",
      "/images/gallery/commode/rest-fertig.jpg",
      "/images/gallery/commode/brand.jpg",
      "/images/gallery/commode/komode-brand.jpg",
      "/images/gallery/commode/detaeil.jpg",
      "/images/gallery/commode/fusz.jpg",
      "/images/gallery/commode/brand-fusz.jpg",
      "/images/gallery/commode/detaiel-.jpg",
      "/images/gallery/commode/detaiel.jpg",
    ],
    image: "/images/gallery/commode/fertig.jpg",
    description: "",
  },
];

export const categories = [
  { value: "all", label: "Alle Arbeiten" },
  { value: "relief", label: "Relief" },
  { value: "objekt", label: "Objekt" },
  { value: "installation", label: "Installation" },
  { value: "projekt", label: "Projekte" },
];
